/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.form;

import java.awt.AlphaComposite;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.UIManager;

/**
 *
 * @author natalija
 */
public class MainFrm extends javax.swing.JFrame {

    /**
     * Creates new form MainFrm
     */
    public MainFrm() {
      try{
            initComponents();
            UIManager.put("MenuItem.font", new Font("Century SchoolBook L", Font.PLAIN, 15));
            getContentPane().setBackground(new Color(222, 239, 245));
            
            this.setLocationRelativeTo(null);
            
            // Postavljanje boje pozadine za meni
            jMenuBar1.setBackground(new Color(173, 216, 230));
            jMenuAranzman.setBackground(new Color(173, 216, 230));
            jMenuKorisnik.setBackground(new Color(173, 216, 230));
            jMenuRezervacija.setBackground(new Color(173, 216, 230));
            jMenuItemKreirajAranžman.setBackground(new Color(173, 216, 230));
            jMenuItemKreirajKorisnika.setBackground(new Color(173, 216, 230));
            jMenuItemKreirajRezervaciju.setBackground(new Color(173, 216, 230));
            jMenuItemPretraziRezervaciju.setBackground(new Color(173, 216, 230));
            jMenuItemPretražiAranžmane.setBackground(new Color(173, 216, 230));
            jMenuItemPretražiKorisnika.setBackground(new Color(173, 216, 230));
            
            
            BufferedImage originalImage = ImageIO.read(new File("/home/natalija/Travel Agency Java/Travel_Agency_Client/src/icon/logo2.png"));
            
            // Smanjivanje slike
            Image scaledImage = originalImage.getScaledInstance(180, 180, Image.SCALE_SMOOTH);

            // Kreiranje BufferedImage sa transparentnom pozadinom
            BufferedImage bufferedImage = new BufferedImage(180, 180, BufferedImage.TYPE_INT_ARGB);
            Graphics2D g2d = bufferedImage.createGraphics();
            g2d.drawImage(scaledImage, 0, 0, null);
            g2d.dispose();

            // Postavljanje ikone na JLabel
            jLabelSlikaa.setIcon(new ImageIcon(bufferedImage));
            jLabelSlika.setVisible(false);
            

        } catch (IOException ex) {
            Logger.getLogger(MainFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
      
       UIManager.put("OptionPane.messageFont", new Font("Century Schoolbook L", Font.BOLD, 14));
        UIManager.put("OptionPane.background", new Color(222, 239, 245));
        UIManager.put("Panel.background", new Color(222, 239, 245));
        UIManager.put("Button.font", new Font("Century Schoolbook L", Font.BOLD, 14));
        UIManager.put("Button.background", new Color(173, 216, 230));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jLabelSlika = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelPrijavljeniZaposleni = new javax.swing.JLabel();
        jButtonKrajRada = new javax.swing.JButton();
        jLabelSlikaa = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuKorisnik = new javax.swing.JMenu();
        jMenuItemKreirajKorisnika = new javax.swing.JMenuItem();
        jMenuItemPretražiKorisnika = new javax.swing.JMenuItem();
        jMenuAranzman = new javax.swing.JMenu();
        jMenuItemKreirajAranžman = new javax.swing.JMenuItem();
        jMenuItemPretražiAranžmane = new javax.swing.JMenuItem();
        jMenuRezervacija = new javax.swing.JMenu();
        jMenuItemKreirajRezervaciju = new javax.swing.JMenuItem();
        jMenuItemPretraziRezervaciju = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jLabelSlika.setIcon(new javax.swing.ImageIcon("/home/natalija/Downloads/logo-removebg-preview.png")); // NOI18N
        jLabelSlika.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Century Schoolbook L", 3, 15)); // NOI18N
        jLabel1.setText("Prijavljeni zaposleni:");

        jLabelPrijavljeniZaposleni.setFont(new java.awt.Font("Century Schoolbook L", 0, 15)); // NOI18N
        jLabelPrijavljeniZaposleni.setText("jLabel2");

        jButtonKrajRada.setBackground(new java.awt.Color(0, 204, 204));
        jButtonKrajRada.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        jButtonKrajRada.setText("Kraj rada");
        jButtonKrajRada.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Century Schoolbook L", 1, 24)); // NOI18N
        jLabel2.setText("Turistička agencija TVOJ SVET");

        jMenuKorisnik.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuKorisnik.setText("Korisnik");
        jMenuKorisnik.setFont(new java.awt.Font("Century Schoolbook L", 0, 17)); // NOI18N
        jMenuKorisnik.setMinimumSize(new java.awt.Dimension(70, 34));
        jMenuKorisnik.setPreferredSize(new java.awt.Dimension(100, 34));

        jMenuItemKreirajKorisnika.setText("Kreiraj korisnika");
        jMenuItemKreirajKorisnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemKreirajKorisnikaActionPerformed(evt);
            }
        });
        jMenuKorisnik.add(jMenuItemKreirajKorisnika);

        jMenuItemPretražiKorisnika.setText("Pretraži korisnike");
        jMenuKorisnik.add(jMenuItemPretražiKorisnika);

        jMenuBar1.add(jMenuKorisnik);

        jMenuAranzman.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuAranzman.setText("Aranžman");
        jMenuAranzman.setFont(new java.awt.Font("Century Schoolbook L", 0, 17)); // NOI18N
        jMenuAranzman.setMinimumSize(new java.awt.Dimension(100, 44));
        jMenuAranzman.setPreferredSize(new java.awt.Dimension(100, 34));

        jMenuItemKreirajAranžman.setText("Kreiraj aranžman");
        jMenuItemKreirajAranžman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemKreirajAranžmanActionPerformed(evt);
            }
        });
        jMenuAranzman.add(jMenuItemKreirajAranžman);

        jMenuItemPretražiAranžmane.setText("Pretraži aranžmane");
        jMenuAranzman.add(jMenuItemPretražiAranžmane);

        jMenuBar1.add(jMenuAranzman);

        jMenuRezervacija.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuRezervacija.setText("Rezervacija");
        jMenuRezervacija.setFont(new java.awt.Font("Century Schoolbook L", 0, 17)); // NOI18N
        jMenuRezervacija.setMinimumSize(new java.awt.Dimension(100, 34));

        jMenuItemKreirajRezervaciju.setText("Kreiraj rezervaciju");
        jMenuItemKreirajRezervaciju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemKreirajRezervacijuActionPerformed(evt);
            }
        });
        jMenuRezervacija.add(jMenuItemKreirajRezervaciju);

        jMenuItemPretraziRezervaciju.setText("Pretraži rezervaciju");
        jMenuRezervacija.add(jMenuItemPretraziRezervaciju);

        jMenuBar1.add(jMenuRezervacija);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabelSlikaa, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonKrajRada, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(40, 40, 40)
                        .addComponent(jLabelPrijavljeniZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelPrijavljeniZaposleni))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonKrajRada, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabelSlikaa, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getjLabelPrijavljeniZaposleni() {
        return jLabelPrijavljeniZaposleni;
    }

    public void setjLabelPrijavljeniZaposleni(JLabel jLabelPrijavljeniZaposleni) {
        this.jLabelPrijavljeniZaposleni = jLabelPrijavljeniZaposleni;
    }

    public JButton getjButtonKrajRada() {
        return jButtonKrajRada;
    }
    

    private void jMenuItemKreirajKorisnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemKreirajKorisnikaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemKreirajKorisnikaActionPerformed

    private void jMenuItemKreirajAranžmanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemKreirajAranžmanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemKreirajAranžmanActionPerformed

    private void jMenuItemKreirajRezervacijuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemKreirajRezervacijuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemKreirajRezervacijuActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonKrajRada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelPrijavljeniZaposleni;
    private javax.swing.JLabel jLabelSlika;
    private javax.swing.JLabel jLabelSlikaa;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenuAranzman;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemKreirajAranžman;
    private javax.swing.JMenuItem jMenuItemKreirajKorisnika;
    private javax.swing.JMenuItem jMenuItemKreirajRezervaciju;
    private javax.swing.JMenuItem jMenuItemPretraziRezervaciju;
    private javax.swing.JMenuItem jMenuItemPretražiAranžmane;
    private javax.swing.JMenuItem jMenuItemPretražiKorisnika;
    private javax.swing.JMenu jMenuKorisnik;
    private javax.swing.JMenu jMenuRezervacija;
    // End of variables declaration//GEN-END:variables

    public void kreirajKorisnikaAddActionListener(ActionListener actionListener) {
        jMenuItemKreirajKorisnika.addActionListener(actionListener);
    }

    public void pretraziKorisnikaAddActionListener(ActionListener actionListener) {
       jMenuItemPretražiKorisnika.addActionListener(actionListener);
    }

    public void kreirajAranzmanAddActionListener(ActionListener actionListener) {
        jMenuItemKreirajAranžman.addActionListener(actionListener);
    }

    public void pretraziAranzmanAddActionListener(ActionListener actionListener) {
       jMenuItemPretražiAranžmane.addActionListener(actionListener);
    }

    public void kreirajRezervacijuAddActionListener(ActionListener actionListener) {
        jMenuItemKreirajRezervaciju.addActionListener(actionListener);
    }

    public void pretraziRezervacijuAddActionListener(ActionListener actionListener) {
        jMenuItemPretraziRezervaciju.addActionListener(actionListener);
    }

    public void krajRadaBtnAddActionListener(ActionListener actionListener) {
        jButtonKrajRada.addActionListener(actionListener);
    }

 
  
}
