/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.form.aranzman;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.UIManager;

/**
 *
 * @author natalija
 */
public class AranzmanFrm extends javax.swing.JDialog {

    /**
     * Creates new form AranzmanFrm2
     */
    public AranzmanFrm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        getContentPane().setBackground(new Color(222, 239, 245));
        jComboBoxDestinacija.setBackground(new Color(173, 216, 230));
        jComboBoxTipAranžmana.setBackground(new Color(173, 216, 230));
         UIManager.put("OptionPane.messageFont", new Font("Century Schoolbook L", Font.BOLD, 14));
        UIManager.put("OptionPane.background", new Color(222, 239, 245));
        UIManager.put("Panel.background", new Color(222, 239, 245));
        UIManager.put("Button.font", new Font("Century Schoolbook L", Font.BOLD, 14));
        UIManager.put("Button.background", new Color(173, 216, 230));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldIDAranžmana = new javax.swing.JTextField();
        jComboBoxTipAranžmana = new javax.swing.JComboBox<>();
        jTextFieldDatumOd = new javax.swing.JTextField();
        jTextFieldDatumDo = new javax.swing.JTextField();
        jComboBoxDestinacija = new javax.swing.JComboBox<>();
        jButtonDodajAranžman = new javax.swing.JButton();
        jLabelID = new javax.swing.JLabel();
        jButtonIzmeniAranžman = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonObrisi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jTextFieldIDAranžmana.setFont(new java.awt.Font("Century Schoolbook L", 0, 17)); // NOI18N
        jTextFieldIDAranžmana.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jComboBoxTipAranžmana.setFont(new java.awt.Font("Century Schoolbook L", 0, 17)); // NOI18N
        jComboBoxTipAranžmana.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextFieldDatumOd.setFont(new java.awt.Font("Century Schoolbook L", 0, 17)); // NOI18N
        jTextFieldDatumOd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextFieldDatumDo.setFont(new java.awt.Font("Century Schoolbook L", 0, 17)); // NOI18N
        jTextFieldDatumDo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jComboBoxDestinacija.setFont(new java.awt.Font("Century Schoolbook L", 0, 17)); // NOI18N
        jComboBoxDestinacija.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonDodajAranžman.setBackground(new java.awt.Color(0, 204, 204));
        jButtonDodajAranžman.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        jButtonDodajAranžman.setText("Dodaj aranžman");

        jLabelID.setFont(new java.awt.Font("Century Schoolbook L", 0, 16)); // NOI18N
        jLabelID.setText("ID aranžmana:");

        jButtonIzmeniAranžman.setBackground(new java.awt.Color(0, 204, 204));
        jButtonIzmeniAranžman.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        jButtonIzmeniAranžman.setText("Izmeni podatke o aranžmanu");

        jLabel2.setFont(new java.awt.Font("Century Schoolbook L", 0, 16)); // NOI18N
        jLabel2.setText("Tip aranžmana:");

        jLabel3.setFont(new java.awt.Font("Century Schoolbook L", 0, 16)); // NOI18N
        jLabel3.setText("Datum od (yyyy-MM-dd):");

        jLabel4.setFont(new java.awt.Font("Century Schoolbook L", 0, 16)); // NOI18N
        jLabel4.setText("Datum do (yyyy-MM-dd):");

        jLabel5.setFont(new java.awt.Font("Century Schoolbook L", 0, 16)); // NOI18N
        jLabel5.setText("Destinacija:");

        jButtonObrisi.setBackground(new java.awt.Color(0, 204, 204));
        jButtonObrisi.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        jButtonObrisi.setText("Obriši aranžman");

        jLabel1.setFont(new java.awt.Font("Century Schoolbook L", 3, 25)); // NOI18N
        jLabel1.setText("FORMA ARANŽMAN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonObrisi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonIzmeniAranžman, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                    .addComponent(jButtonDodajAranžman, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBoxDestinacija, javax.swing.GroupLayout.Alignment.LEADING, 0, 366, Short.MAX_VALUE)
                            .addComponent(jTextFieldDatumDo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDatumOd, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxTipAranžmana, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldIDAranžmana, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(45, 45, 45))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(93, 93, 93))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldIDAranžmana, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxTipAranžmana, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldDatumOd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldDatumDo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelID)
                        .addGap(144, 144, 144)))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxDestinacija, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jButtonDodajAranžman, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonIzmeniAranžman, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    public JButton getjButtonDodajAranžman() {
        return jButtonDodajAranžman;
    }

    public JButton getjButtonIzmeniAranžman() {
        return jButtonIzmeniAranžman;
    }

    public JComboBox<Object> getjComboBoxDestinacija() {
        return jComboBoxDestinacija;
    }

    public JComboBox<Object> getjComboBoxTipAranžmana() {
        return jComboBoxTipAranžmana;
    }

    public JTextField getjTextFieldDatumDo() {
        return jTextFieldDatumDo;
    }

    public JTextField getjTextFieldDatumOd() {
        return jTextFieldDatumOd;
    }

    public JLabel getjLabelID() {
        return jLabelID;
    }

    public void setjLabelID(JLabel jLabelID) {
        this.jLabelID = jLabelID;
    }

    public JButton getjButtonObrisi() {
        return jButtonObrisi;
    }

    public void setjButtonObrisi(JButton jButtonObrisi) {
        this.jButtonObrisi = jButtonObrisi;
    }

    /**
     * @param args the command line arguments
     */
    public JTextField getjTextFieldIDAranžmana() {
        return jTextFieldIDAranžmana;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodajAranžman;
    private javax.swing.JButton jButtonIzmeniAranžman;
    private javax.swing.JButton jButtonObrisi;
    private javax.swing.JComboBox<Object> jComboBoxDestinacija;
    private javax.swing.JComboBox<Object> jComboBoxTipAranžmana;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JTextField jTextFieldDatumDo;
    private javax.swing.JTextField jTextFieldDatumOd;
    private javax.swing.JTextField jTextFieldIDAranžmana;
    // End of variables declaration//GEN-END:variables

    public void dodajAranzmanBtnAddActionListener(ActionListener actionListener) {
        jButtonDodajAranžman.addActionListener(actionListener);
    }

    public void izmeniAranzmanBtnAddActionListener(ActionListener actionListener) {
        jButtonIzmeniAranžman.addActionListener(actionListener);
    }

    public void obrisiBtnAddActionListener(ActionListener actionListener) {
        jButtonObrisi.addActionListener(actionListener);
    }
}
