/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.form.aranzman;

import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;

/**
 *
 * @author natalija
 */
public class PretragaAranzmanaFrm extends javax.swing.JDialog {

    /**
     * Creates new form PretragaAranzmanaFrm2
     */
    public PretragaAranzmanaFrm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        getContentPane().setBackground(new Color(222, 239, 245));
        JTableHeader header = jTableAranžman.getTableHeader();
        header.setDefaultRenderer(new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                JLabel label = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                label.setFont(new Font("Century Schoolbook L", Font.BOLD, 16));
                label.setBackground(new Color(173, 216, 230));
                label.setForeground(Color.BLACK);
                label.setHorizontalAlignment(SwingConstants.CENTER);  // Centriranje teksta
                label.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 1, Color.GRAY));  // Crtice između kolona
                return label;
            }
        });
        
        UIManager.put("OptionPane.messageFont", new Font("Century Schoolbook L", Font.BOLD, 14));
        UIManager.put("OptionPane.background", new Color(222, 239, 245));
        UIManager.put("Panel.background", new Color(222, 239, 245));
        UIManager.put("Button.font", new Font("Century Schoolbook L", Font.BOLD, 14));
        UIManager.put("Button.background", new Color(173, 216, 230));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButtonPretraga = new javax.swing.JButton();
        jButtonResetujPretragu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAranžman = new javax.swing.JTable();
        jButtonDetalji = new javax.swing.JButton();
        jTextFieldTipAranzmana = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Century Schoolbook L", 2, 16)); // NOI18N
        jLabel2.setText("Pretraga aranžmana po tipu:");

        jButtonPretraga.setBackground(new java.awt.Color(0, 204, 204));
        jButtonPretraga.setFont(new java.awt.Font("Century Schoolbook L", 1, 17)); // NOI18N
        jButtonPretraga.setText("Pretraga");
        jButtonPretraga.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonResetujPretragu.setBackground(new java.awt.Color(0, 204, 204));
        jButtonResetujPretragu.setFont(new java.awt.Font("Century Schoolbook L", 1, 17)); // NOI18N
        jButtonResetujPretragu.setText("Resetuj pretragu");
        jButtonResetujPretragu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTableAranžman.setFont(new java.awt.Font("Century Schoolbook L", 0, 16)); // NOI18N
        jTableAranžman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableAranžman.setGridColor(new java.awt.Color(173, 216, 230));
        jTableAranžman.setRowHeight(24);
        jTableAranžman.setSelectionBackground(new java.awt.Color(173, 216, 230));
        jScrollPane1.setViewportView(jTableAranžman);

        jButtonDetalji.setBackground(new java.awt.Color(0, 204, 204));
        jButtonDetalji.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        jButtonDetalji.setText("Detalji");
        jButtonDetalji.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextFieldTipAranzmana.setFont(new java.awt.Font("Century Schoolbook L", 0, 17)); // NOI18N
        jTextFieldTipAranzmana.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Century Schoolbook L", 3, 24)); // NOI18N
        jLabel1.setText("Pretraga aranžmana");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel2)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jTextFieldTipAranzmana, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonResetujPretragu, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(44, 56, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonDetalji, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldTipAranzmana, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonResetujPretragu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonDetalji, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
  public JButton getjButtonAžurirajAranžman() {
        return jButtonDetalji;
    }


    public JButton getjButtonPretraga() {
        return jButtonPretraga;
    }

    public JButton getjButtonResetujPretragu() {
        return jButtonResetujPretragu;
    }

 

    public JTextField getjTextFieldTipAranzmana() {
        return jTextFieldTipAranzmana;
    }

    public void setjTextFieldTipAranzmana(JTextField jTextFieldTipAranzmana) {
        this.jTextFieldTipAranzmana = jTextFieldTipAranzmana;
    }

    public JTable getjTableAranžman() {
        return jTableAranžman;
    }

    public void setjTableAranžman(JTable jTableAranžman) {
        this.jTableAranžman = jTableAranžman;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDetalji;
    private javax.swing.JButton jButtonPretraga;
    private javax.swing.JButton jButtonResetujPretragu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAranžman;
    private javax.swing.JTextField jTextFieldTipAranzmana;
    // End of variables declaration//GEN-END:variables

  

    public void pretragaBtnAddActionListener(ActionListener actionListener) {
        jButtonPretraga.addActionListener(actionListener);
    }

    public void resetujBtnAddActionListener(ActionListener actionListener) {
        jButtonResetujPretragu.addActionListener(actionListener);
    }

    public void detaljiBtnAddActionListener(ActionListener actionListener) {
        jButtonDetalji.addActionListener(actionListener);
    }
}
