/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.form;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionListener;
import javax.accessibility.AccessibleContext;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JRootPane;
import javax.swing.UIManager;

/**
 *
 * @author natalija
 */
public class ServerFrm extends javax.swing.JFrame {

    /**
     * Creates new form ServerForm
     */
    public ServerFrm() {
        initComponents();
   
        getContentPane().setBackground(new Color(222, 239, 245));
        this.setLocationRelativeTo(null);

        // Postavljanje boje pozadine za meni
        jMenuBar1.setBackground(new Color(173, 216, 230));
        jMenu1.setBackground(new Color(173, 216, 230));
        jMenuOSoftveru.setBackground(new Color(173, 216, 230));
        jMenuItemBaza.setBackground(new Color(173, 216, 230));
        jMenuItemAutorSoftvera.setBackground(new Color(173, 216, 230));

        UIManager.put("OptionPane.messageFont", new Font("Century Schoolbook L", Font.BOLD, 14));
        UIManager.put("OptionPane.background", new Color(222, 239, 245));
        UIManager.put("Panel.background", new Color(222, 239, 245));
        UIManager.put("Button.font", new Font("Century Schoolbook L", Font.BOLD, 14));
        UIManager.put("Button.background", new Color(173, 216, 230));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelStatusServera = new javax.swing.JLabel();
        jButtonPokreniServer = new javax.swing.JButton();
        jButtonZaustaviServer = new javax.swing.JButton();
        jLabelStatus = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelSLika = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemBaza = new javax.swing.JMenuItem();
        jMenuOSoftveru = new javax.swing.JMenu();
        jMenuItemAutorSoftvera = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Abyssinica SIL", 3, 15)); // NOI18N
        jLabel1.setText("Status servera");

        jButtonPokreniServer.setBackground(new java.awt.Color(0, 204, 204));
        jButtonPokreniServer.setFont(new java.awt.Font("Abyssinica SIL", 1, 15)); // NOI18N
        jButtonPokreniServer.setText("Pokreni server");
        jButtonPokreniServer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonPokreniServer.setPreferredSize(new java.awt.Dimension(129, 36));

        jButtonZaustaviServer.setBackground(new java.awt.Color(0, 204, 204));
        jButtonZaustaviServer.setFont(new java.awt.Font("Abyssinica SIL", 1, 15)); // NOI18N
        jButtonZaustaviServer.setText("Zaustavi server");
        jButtonZaustaviServer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonZaustaviServer.setPreferredSize(new java.awt.Dimension(135, 36));

        jLabelStatus.setFont(new java.awt.Font("Abyssinica SIL", 0, 15)); // NOI18N

        jLabel2.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 20)); // NOI18N
        jLabel2.setText("Turistička agencija TVOJ SVET");

        jMenuBar1.setMaximumSize(new java.awt.Dimension(280, 32768));
        jMenuBar1.setMinimumSize(new java.awt.Dimension(280, 200));

        jMenu1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu1.setText("Podešavanja");
        jMenu1.setFont(new java.awt.Font("Abyssinica SIL", 0, 15)); // NOI18N
        jMenu1.setMinimumSize(new java.awt.Dimension(100, 100));
        jMenu1.setPreferredSize(new java.awt.Dimension(100, 30));

        jMenuItemBaza.setFont(new java.awt.Font("Abyssinica SIL", 0, 15)); // NOI18N
        jMenuItemBaza.setText("baza");
        jMenu1.add(jMenuItemBaza);

        jMenuBar1.add(jMenu1);

        jMenuOSoftveru.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuOSoftveru.setText("O softveru");
        jMenuOSoftveru.setFont(new java.awt.Font("Abyssinica SIL", 0, 15)); // NOI18N
        jMenuOSoftveru.setPreferredSize(new java.awt.Dimension(100, 30));

        jMenuItemAutorSoftvera.setFont(new java.awt.Font("Abyssinica SIL", 0, 15)); // NOI18N
        jMenuItemAutorSoftvera.setText("autor softvera");
        jMenuOSoftveru.add(jMenuItemAutorSoftvera);

        jMenuBar1.add(jMenuOSoftveru);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLabelStatusServera, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(58, 58, 58)
                                .addComponent(jLabelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonPokreniServer, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(jButtonZaustaviServer, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 20, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(jLabelSLika)
                        .addGap(29, 29, 29))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabelSLika, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelStatusServera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPokreniServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonZaustaviServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPokreniServer;
    private javax.swing.JButton jButtonZaustaviServer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelSLika;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelStatusServera;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAutorSoftvera;
    private javax.swing.JMenuItem jMenuItemBaza;
    private javax.swing.JMenu jMenuOSoftveru;
    // End of variables declaration//GEN-END:variables

  
    public void addPokreniServerBtnActionListener(ActionListener actionListener) {
        jButtonPokreniServer.addActionListener(actionListener);
    }

    public void addZaustaviServerActionListener(ActionListener actionListener) {
       jButtonZaustaviServer.addActionListener(actionListener);
    }
    
    public void addBazaActionListener(ActionListener actionListener) {
       jMenuItemBaza.addActionListener(actionListener);
    }

    public void addOAutoruActionListener(ActionListener actionListener) {
        jMenuItemAutorSoftvera.addActionListener(actionListener);
    }

    public JButton getjButtonPokreniServer() {
        return jButtonPokreniServer;
    }

    public JButton getjButtonZaustaviServer() {
        return jButtonZaustaviServer;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public JMenuItem getjMenuItemBaza() {
        return jMenuItemBaza;
    }

    public JLabel getjLabelStatus() {
        return jLabelStatus;
    }

    public void setjLabelStatus(JLabel jLabelStatus) {
        this.jLabelStatus = jLabelStatus;
    }

    public JLabel getjLabelSLika() {
        return jLabelSLika;
    }

 




    
    
    
}
